# Generated by Django 6.0.2 on 2026-02-12 14:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Tema')),
                ('resumo', models.TextField(verbose_name='Resumo / Propósito')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Recurso / Ferramenta')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('tipo', models.CharField(help_text='Ex: Artigo, Vídeo, Curso, Livro, Tutorial, Podcast, etc.', max_length=100, verbose_name='Tipo')),
                ('url', models.URLField(help_text='Endereço web completo (ex: https://...)', verbose_name='Link de Acesso')),
                ('catalogado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Catalogação')),
                ('gratuito', models.BooleanField(default=True, verbose_name='É gratuito? (Aberto/Gratuito)')),
                ('prestigio', models.IntegerField(default=0, help_text='Será usado no futuro para ordenação por popularidade/votos', verbose_name='Contador de Prestígio')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='beplinks.tema', verbose_name='Tema / Eixo')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['-prestigio', 'nome'],
            },
        ),
    ]
